services:
  postgres:
    image: postgres:15.0-alpine
    container_name: customPostgreDbContainer
    hostname: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: testDb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
